"""scripts/docs/_common.py — Shared helpers for doc generators.

Centralizes: project root resolution, atomic file write with hash diff,
git commit short SHA, generation timestamp, banner header injection.
"""
from __future__ import annotations

import hashlib
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parent.parent.parent
DOCS_DIR = ROOT / "docs"
REF_DIR = DOCS_DIR / "reference"


def git_short_sha() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, text=True
        ).strip()
    except Exception:
        return "unknown"


def now_iso() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


BANNER = (
    "<!-- AUTO-GENERATED by scripts/docs — DO NOT EDIT BY HAND.\n"
    "     Regenerate with `make docs` (or `python3 scripts/docs/gen_all.py`).\n"
    "     Source of truth: {source}\n"
    "     Generated: {ts}  ·  git: {sha}\n"
    "-->\n\n"
)


def write_doc(path: Path, source: str, body: str) -> tuple[bool, Path]:
    """Write doc with banner; return (changed, path).
    Skips write if structural content (ignoring timestamp) is unchanged, so
    `make docs` is idempotent and CI `git diff --exit-code` is reliable.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    content = BANNER.format(source=source, ts=now_iso(), sha=git_short_sha()) + body
    new_hash = hashlib.sha256(_strip_ts(content).encode()).hexdigest()
    if path.exists():
        old_hash = hashlib.sha256(_strip_ts(path.read_text()).encode()).hexdigest()
        if old_hash == new_hash:
            return False, path
    path.write_text(content)
    return True, path


def _strip_ts(s: str) -> str:
    return "\n".join(l for l in s.splitlines() if "Generated:" not in l)


def rel(p: Path) -> str:
    return p.resolve().relative_to(ROOT).as_posix()


def md_escape_pipe(s: str) -> str:
    return (s or "").replace("|", "\\|").replace("\n", " ").strip()


def md_table(headers: Iterable[str], rows: Iterable[Iterable[str]]) -> str:
    headers = list(headers)
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join(["---"] * len(headers)) + "|"]
    for r in rows:
        out.append("| " + " | ".join(md_escape_pipe(c) for c in r) + " |")
    return "\n".join(out) + "\n"
